# Generated by Django 3.2.5 on 2021-11-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="users", name="is_admin", field=models.BooleanField(default=0)
        )
    ]
