# Generated by Django 3.2.5 on 2021-11-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0002_users_is_admin")]

    operations = [
        migrations.RenameField(
            model_name="users", old_name="is_admin", new_name="level"
        ),
        migrations.AddField(
            model_name="session", name="level", field=models.BooleanField(null=True)
        ),
    ]
