# Generated by Django 3.2.5 on 2021-11-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0003_auto_20211111_1949")]

    operations = [
        migrations.AlterField(
            model_name="session", name="level", field=models.IntegerField(null=True)
        ),
        migrations.AlterField(
            model_name="users", name="level", field=models.IntegerField(default=0)
        ),
    ]
