# Generated by Django 3.2.5 on 2021-11-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0004_auto_20211111_2031")]

    operations = [
        migrations.AddField(
            model_name="transactions", name="message", field=models.TextField(null=True)
        )
    ]
