# Generated by Django 3.2.5 on 2021-11-14 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0005_transactions_message")]

    operations = [
        migrations.AddField(
            model_name="itemtransactions",
            name="discount",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="itemtransactions",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="itemtransactions",
            name="price",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="itemtransactions",
            name="amount",
            field=models.IntegerField(null=True),
        ),
    ]
