# Generated by Django 3.2.5 on 2021-11-14 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0006_auto_20211114_1005")]

    operations = [
        migrations.AddField(
            model_name="itemtransactions",
            name="total_price",
            field=models.IntegerField(null=True),
        )
    ]
