# Generated by Django 3.2.5 on 2021-11-14 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0007_itemtransactions_total_price")]

    operations = [
        migrations.AlterField(
            model_name="transactions",
            name="id",
            field=models.UUIDField(primary_key=True, serialize=False),
        )
    ]
