# Generated by Django 3.2.9 on 2021-11-11 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0002_alter_session_is_active")]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="expired_at",
            field=models.DateTimeField(null=True),
        )
    ]
