# Generated by Django 3.2.9 on 2021-11-11 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0004_session_token")]

    operations = [
        migrations.AlterField(
            model_name="items",
            name="category",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="items",
            name="discount",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="items",
            name="image",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="items", name="price", field=models.IntegerField(null=True)
        ),
    ]
